name: Pull Request Closed Action

on:
  workflow_dispatch:
  pull_request:
    types:
    - closed
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run hello script
        run: |
          echo Hello, Github Actions!
          echo This script runs at a Pull Resut Closed.
