name: Pull Request Action

on:
  workflow_dispatch:
  pull_request:
    branches:
     - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run hello script
        run: |
          echo Hello, Github Actions!
          echo This script runs at a Pull Request is created or changed.
