name: Pull Request Action

on:
  workflow_dispatch:
  pull_request:
    branches:
     - '**'

jobs:
  hello-message:
    runs-on: ubuntu-latest

    steps:
      - name: Run hello script
        run: |
          echo Hello, Github Actions!
          echo This script runs at a Pull Request is created or changed.
          echo "This workflow was triggered on branch ${{ github.ref }}"
          echo "The commit message is ${GITHUB_EVENT_PATH}"
